replicaCount: 1

image:
  repository: 158527855865.dkr.ecr.ap-south-1.amazonaws.com/helm-nginx
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

livenessProbe:
  path: /healthz
  initialDelaySeconds: 15
  periodSeconds: 10

readinessProbe:
  path: /healthz
  initialDelaySeconds: 5
  periodSeconds: 5

ingress:
  enabled: false
